### ISSUE TITLE
'toDic' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by ShaoAsher** [AAChartModel/AAChartKit-Swift#97]
无法使用

**Comment by AAChartModel** [comment]
你是通过 pod 导入的? pod 上的 代码不是最新的,你暂时还是用手动拖入的方式导入吧

**Comment by RomuloVHSYS** [comment]
Check this related problem: [#88](https://github.com/AAChartModel/AAChartKit-Swift/issues/88)

And try to import the pod like that way:

`pod 'AAInfographics', :git => 'https://github.com/AAChartKit/AAChartKit-Swift.git', :branch => 'master'`

The problem is some methods that weren't public, and is solved but not updated on CocoaPods

**Comment by RomuloVHSYS** [comment]
Importing pod that way, you are able to get updated code directly on the master branch, without a tag.

**Comment by SreekanthGudisi** [comment]
HI,

I fixed this way

installed pod via
`pod 'AAInfographics', :git => 'https://github.com/AAChartKit/AAChartKit-Swift.git', :branch => 'master'`

**Deployment Target** 
I was using 12.2 now i changed to 10.0 it's working
